if(NOT DEFINED STAMP_KEY_FILE OR STAMP_KEY_FILE STREQUAL "")
  message(FATAL_ERROR "STAMP_KEY_FILE is required")
endif()

if(NOT DEFINED STAMP_SECRET_HEADER OR STAMP_SECRET_HEADER STREQUAL "")
  message(FATAL_ERROR "STAMP_SECRET_HEADER is required")
endif()

if(NOT DEFINED STAMP_PAYLOAD_FILE OR STAMP_PAYLOAD_FILE STREQUAL "")
  message(FATAL_ERROR "STAMP_PAYLOAD_FILE is required")
endif()

if(NOT EXISTS "${STAMP_KEY_FILE}")
  message(FATAL_ERROR "Stamp key file not found: ${STAMP_KEY_FILE}")
endif()

if(NOT EXISTS "${STAMP_PAYLOAD_FILE}")
  message(FATAL_ERROR "Stamp payload file not found: ${STAMP_PAYLOAD_FILE}")
endif()

file(READ "${STAMP_KEY_FILE}" stamp_key_hex)
string(REGEX REPLACE "[ \t\r\n]" "" stamp_key_hex "${stamp_key_hex}")
string(TOLOWER "${stamp_key_hex}" stamp_key_hex)
string(LENGTH "${stamp_key_hex}" stamp_key_hex_length)

file(READ "${STAMP_PAYLOAD_FILE}" stamp_payload_hex HEX)
string(TOLOWER "${stamp_payload_hex}" stamp_payload_hex)
string(LENGTH "${stamp_payload_hex}" stamp_payload_hex_length)
math(EXPR stamp_payload_size "${stamp_payload_hex_length} / 2")

if(NOT stamp_key_hex MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Stamp key must contain only hexadecimal characters: ${STAMP_KEY_FILE}")
endif()

if(NOT stamp_key_hex_length EQUAL 64)
  message(FATAL_ERROR "Stamp key must be exactly 32 bytes encoded as 64 hex characters: ${STAMP_KEY_FILE}")
endif()

if(stamp_payload_size LESS 1)
  message(FATAL_ERROR "Stamp payload file is empty: ${STAMP_PAYLOAD_FILE}")
endif()

set(hex_digits 0 1 2 3 4 5 6 7 8 9 a b c d e f)

function(random_byte out_var)
  string(RANDOM LENGTH 2 ALPHABET "0123456789abcdef" random_hex)
  math(EXPR random_value "0x${random_hex}")
  set(${out_var} "${random_value}" PARENT_SCOPE)
endfunction()

function(format_byte value out_var)
  math(EXPR byte_value "${value} & 255")
  math(EXPR high_nibble "${byte_value} / 16")
  math(EXPR low_nibble "${byte_value} % 16")
  list(GET hex_digits ${high_nibble} high_hex)
  list(GET hex_digits ${low_nibble} low_hex)
  set(${out_var} "${high_hex}${low_hex}" PARENT_SCOPE)
endfunction()

function(rotl8 value bits out_var)
  math(EXPR byte_value "${value} & 255")
  math(EXPR shift "${bits} % 8")
  if(shift EQUAL 0)
    set(rotated "${byte_value}")
  else()
    math(EXPR rotated "(((${byte_value} << ${shift}) | (${byte_value} >> (8 - ${shift}))) & 255)")
  endif()
  set(${out_var} "${rotated}" PARENT_SCOPE)
endfunction()

function(mod_inverse_256 value out_var)
  foreach(candidate RANGE 1 255)
    math(EXPR product "(${value} * ${candidate}) % 256")
    if(product EQUAL 1)
      set(${out_var} "${candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "Cannot invert ${value} modulo 256")
endfunction()

function(byte_list_to_initializer list_name out_var)
  set(initializer "")
  foreach(value IN LISTS ${list_name})
    format_byte("${value}" byte_hex)
    if(initializer STREQUAL "")
      set(initializer "0x${byte_hex}")
    else()
      string(APPEND initializer ", 0x${byte_hex}")
    endif()
  endforeach()
  set(${out_var} "${initializer}" PARENT_SCOPE)
endfunction()

function(uint_list_to_initializer list_name out_var)
  set(initializer "")
  foreach(value IN LISTS ${list_name})
    if(initializer STREQUAL "")
      set(initializer "${value}u")
    else()
      string(APPEND initializer ", ${value}u")
    endif()
  endforeach()
  set(${out_var} "${initializer}" PARENT_SCOPE)
endfunction()

function(random_payload_index out_var)
  random_byte(index_a)
  random_byte(index_b)
  random_byte(index_c)
  random_byte(index_d)
  math(EXPR index_value "(((${index_a} * 16777216) + (${index_b} * 65536) + (${index_c} * 256) + ${index_d}) % ${stamp_payload_size})")
  set(${out_var} "${index_value}" PARENT_SCOPE)
endfunction()

function(payload_byte_at index out_var)
  math(EXPR payload_index "(${index}) % ${stamp_payload_size}")
  math(EXPR payload_offset "${payload_index} * 2")
  string(SUBSTRING "${stamp_payload_hex}" ${payload_offset} 2 payload_byte_hex)
  math(EXPR payload_byte_value "0x${payload_byte_hex}")
  set(${out_var} "${payload_byte_value}" PARENT_SCOPE)
endfunction()

set(stamp_key_bytes "")
foreach(index RANGE 0 31)
  math(EXPR offset "${index} * 2")
  string(SUBSTRING "${stamp_key_hex}" ${offset} 2 byte_hex)
  math(EXPR byte_value "0x${byte_hex}")
  list(APPEND stamp_key_bytes "${byte_value}")
endforeach()

random_byte(payload_size_seed)
math(EXPR stamp_secret_payload_size "96 + (${payload_size_seed} % 65)")

set(stamp_secret_payload "")
set(stamp_secret_payload_literal "")
foreach(index RANGE 1 ${stamp_secret_payload_size})
  random_byte(payload_byte)
  list(APPEND stamp_secret_payload "${payload_byte}")
  format_byte("${payload_byte}" payload_byte_hex)
  string(APPEND stamp_secret_payload_literal "\\x${payload_byte_hex}")
endforeach()

random_byte(rolling_seed)
random_byte(rolling_multiplier_seed)
math(EXPR rolling_multiplier "(${rolling_multiplier_seed} | 1)")
set(rolling "${rolling_seed}")

set(remaining_indices "")
foreach(index RANGE 0 31)
  list(APPEND remaining_indices "${index}")
endforeach()

set(stamp_secret_encoded "")
set(stamp_secret_out_index "")
set(stamp_secret_payload_a "")
set(stamp_secret_payload_b "")
set(stamp_secret_mask "")
set(stamp_secret_add "")
set(stamp_secret_inv_mul "")
set(stamp_secret_rotate "")
set(stamp_secret_salt "")
set(stamp_secret_embedded_a "")
set(stamp_secret_embedded_b "")
set(stamp_secret_embedded_mul "")

foreach(entry RANGE 0 31)
  list(LENGTH remaining_indices remaining_count)
  random_byte(permutation_seed)
  math(EXPR remaining_pick "${permutation_seed} % ${remaining_count}")
  list(GET remaining_indices ${remaining_pick} out_index)
  list(REMOVE_AT remaining_indices ${remaining_pick})
  list(GET stamp_key_bytes ${out_index} key_byte)

  random_byte(payload_a_seed)
  random_byte(payload_b_seed)
  math(EXPR payload_a_index "${payload_a_seed} % ${stamp_secret_payload_size}")
  math(EXPR payload_b_index "${payload_b_seed} % ${stamp_secret_payload_size}")
  list(GET stamp_secret_payload ${payload_a_index} payload_a)
  list(GET stamp_secret_payload ${payload_b_index} payload_b)

  random_byte(mask)
  random_byte(add)
  random_byte(multiplier_seed)
  math(EXPR multiplier "(${multiplier_seed} | 1)")
  mod_inverse_256("${multiplier}" inv_multiplier)
  random_byte(rotate_seed)
  math(EXPR rotate "${rotate_seed} % 8")
  random_byte(salt)
  random_payload_index(embedded_a_index)
  random_payload_index(embedded_b_index)
  random_byte(embedded_multiplier_seed)
  math(EXPR embedded_multiplier "(${embedded_multiplier_seed} | 1)")

  math(EXPR embedded_a_runtime_index "(${embedded_a_index} + ${payload_a} + ${rolling}) % ${stamp_payload_size}")
  math(EXPR embedded_b_runtime_index "(${embedded_b_index} + ${salt} + ${entry} + ${payload_b}) % ${stamp_payload_size}")
  payload_byte_at("${embedded_a_runtime_index}" embedded_a)
  payload_byte_at("${embedded_b_runtime_index}" embedded_b)

  math(EXPR dynamic_source "((${payload_b} ^ ${embedded_a}) + ${rolling} + ${entry} + ${salt} + (${embedded_b} * ${embedded_multiplier})) % 256")
  rotl8("${dynamic_source}" "${rotate}" dynamic)
  math(EXPR mixed "${key_byte} ^ ${mask} ^ ${payload_a} ^ ${dynamic}")
  math(EXPR encoded "((${mixed} * ${multiplier}) + ${add}) % 256")

  math(EXPR decoded_step "(${encoded} - ${add} + 256) % 256")
  math(EXPR decoded_step "(${decoded_step} * ${inv_multiplier}) % 256")
  math(EXPR decoded "${decoded_step} ^ ${mask} ^ ${payload_a} ^ ${dynamic}")
  if(NOT decoded EQUAL key_byte)
    message(FATAL_ERROR "Internal stamp key obfuscation self-check failed at byte ${out_index}")
  endif()

  list(APPEND stamp_secret_encoded "${encoded}")
  list(APPEND stamp_secret_out_index "${out_index}")
  list(APPEND stamp_secret_payload_a "${payload_a_index}")
  list(APPEND stamp_secret_payload_b "${payload_b_index}")
  list(APPEND stamp_secret_mask "${mask}")
  list(APPEND stamp_secret_add "${add}")
  list(APPEND stamp_secret_inv_mul "${inv_multiplier}")
  list(APPEND stamp_secret_rotate "${rotate}")
  list(APPEND stamp_secret_salt "${salt}")
  list(APPEND stamp_secret_embedded_a "${embedded_a_index}")
  list(APPEND stamp_secret_embedded_b "${embedded_b_index}")
  list(APPEND stamp_secret_embedded_mul "${embedded_multiplier}")

  math(EXPR rolling "(${rolling} * ${rolling_multiplier} + ${encoded} + ${payload_a} + ${embedded_b} + ${salt}) % 256")
endforeach()

byte_list_to_initializer(stamp_secret_encoded stamp_secret_encoded_initializer)
byte_list_to_initializer(stamp_secret_out_index stamp_secret_out_index_initializer)
byte_list_to_initializer(stamp_secret_payload_a stamp_secret_payload_a_initializer)
byte_list_to_initializer(stamp_secret_payload_b stamp_secret_payload_b_initializer)
byte_list_to_initializer(stamp_secret_mask stamp_secret_mask_initializer)
byte_list_to_initializer(stamp_secret_add stamp_secret_add_initializer)
byte_list_to_initializer(stamp_secret_inv_mul stamp_secret_inv_mul_initializer)
byte_list_to_initializer(stamp_secret_rotate stamp_secret_rotate_initializer)
byte_list_to_initializer(stamp_secret_salt stamp_secret_salt_initializer)
uint_list_to_initializer(stamp_secret_embedded_a stamp_secret_embedded_a_initializer)
uint_list_to_initializer(stamp_secret_embedded_b stamp_secret_embedded_b_initializer)
byte_list_to_initializer(stamp_secret_embedded_mul stamp_secret_embedded_mul_initializer)
format_byte("${rolling_seed}" rolling_seed_hex)
format_byte("${rolling_multiplier}" rolling_multiplier_hex)

get_filename_component(stamp_secret_dir "${STAMP_SECRET_HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${stamp_secret_dir}")

set(stamp_secret_header "#pragma once\n\n")
string(APPEND stamp_secret_header "#ifndef ELTEN_GENERATED_STAMP_SECRET_H\n")
string(APPEND stamp_secret_header "#define ELTEN_GENERATED_STAMP_SECRET_H\n\n")
string(APPEND stamp_secret_header "#include <cstddef>\n")
string(APPEND stamp_secret_header "#include <cstdint>\n\n")
string(APPEND stamp_secret_header "#define SECR \"${stamp_secret_payload_literal}\"\n")
string(APPEND stamp_secret_header "#define ELTEN_STAMP_SECRET_PAYLOAD_SIZE ${stamp_secret_payload_size}u\n\n")
string(APPEND stamp_secret_header "namespace EltenGeneratedStampSecret {\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kEncoded[32] = { ${stamp_secret_encoded_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kOutIndex[32] = { ${stamp_secret_out_index_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kPayloadA[32] = { ${stamp_secret_payload_a_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kPayloadB[32] = { ${stamp_secret_payload_b_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kMask[32] = { ${stamp_secret_mask_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kAdd[32] = { ${stamp_secret_add_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kInvMul[32] = { ${stamp_secret_inv_mul_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kRotate[32] = { ${stamp_secret_rotate_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kSalt[32] = { ${stamp_secret_salt_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint32_t kEmbeddedA[32] = { ${stamp_secret_embedded_a_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint32_t kEmbeddedB[32] = { ${stamp_secret_embedded_b_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kEmbeddedMul[32] = { ${stamp_secret_embedded_mul_initializer} };\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kRollingSeed = 0x${rolling_seed_hex};\n")
string(APPEND stamp_secret_header "static constexpr std::uint8_t kRollingMultiplier = 0x${rolling_multiplier_hex};\n\n")
string(APPEND stamp_secret_header "inline std::uint8_t payload_byte(const char *payload, std::uint8_t index) {\n")
string(APPEND stamp_secret_header "  return static_cast<std::uint8_t>(static_cast<unsigned char>(payload[index % ELTEN_STAMP_SECRET_PAYLOAD_SIZE]));\n")
string(APPEND stamp_secret_header "}\n\n")
string(APPEND stamp_secret_header "inline std::uint8_t rotl8(std::uint8_t value, std::uint8_t bits) {\n")
string(APPEND stamp_secret_header "  bits = static_cast<std::uint8_t>(bits & 7u);\n")
string(APPEND stamp_secret_header "  return bits == 0 ? value : static_cast<std::uint8_t>((value << bits) | (value >> (8u - bits)));\n")
string(APPEND stamp_secret_header "}\n")
string(APPEND stamp_secret_header "} // namespace EltenGeneratedStampSecret\n\n")
string(APPEND stamp_secret_header "inline void genkey(const char *payload, char *key) {\n")
string(APPEND stamp_secret_header "  using namespace EltenGeneratedStampSecret;\n")
string(APPEND stamp_secret_header "  std::uint8_t rolling = kRollingSeed;\n")
string(APPEND stamp_secret_header "  for (std::uint8_t entry = 0; entry < 32u; ++entry) {\n")
string(APPEND stamp_secret_header "    const std::uint8_t payload_a = payload_byte(payload, kPayloadA[entry]);\n")
string(APPEND stamp_secret_header "    const std::uint8_t payload_b = payload_byte(payload, kPayloadB[entry]);\n")
string(APPEND stamp_secret_header "    const std::uint8_t embedded_a = EltenLauncher::EmbeddedRubyPayloadByte(kEmbeddedA[entry] + payload_a + rolling);\n")
string(APPEND stamp_secret_header "    const std::uint8_t embedded_b = EltenLauncher::EmbeddedRubyPayloadByte(kEmbeddedB[entry] + kSalt[entry] + entry + payload_b);\n")
string(APPEND stamp_secret_header "    const std::uint8_t dynamic = rotl8(static_cast<std::uint8_t>((payload_b ^ embedded_a) + rolling + entry + kSalt[entry] + static_cast<std::uint8_t>(embedded_b * kEmbeddedMul[entry])), kRotate[entry]);\n")
string(APPEND stamp_secret_header "    std::uint8_t value = static_cast<std::uint8_t>(kEncoded[entry] - kAdd[entry]);\n")
string(APPEND stamp_secret_header "    value = static_cast<std::uint8_t>(value * kInvMul[entry]);\n")
string(APPEND stamp_secret_header "    value = static_cast<std::uint8_t>(value ^ kMask[entry] ^ payload_a ^ dynamic);\n")
string(APPEND stamp_secret_header "    key[kOutIndex[entry]] = static_cast<char>(value);\n")
string(APPEND stamp_secret_header "    rolling = static_cast<std::uint8_t>(rolling * kRollingMultiplier + kEncoded[entry] + payload_a + embedded_b + kSalt[entry]);\n")
string(APPEND stamp_secret_header "  }\n")
string(APPEND stamp_secret_header "}\n\n")
string(APPEND stamp_secret_header "#endif\n")

file(WRITE "${STAMP_SECRET_HEADER}" "${stamp_secret_header}")
